# Perfil local de desarrollo
app.pdf.allow-localhost-services=true
app.pdf.gotenberg.url=${APP_PDF_GOTENBERG_URL:http://localhost:3000/forms/libreoffice/convert}
app.docxtemplater.url=${APP_DOCXTEMPLATER_URL:http://localhost:3001/render-docx}

