import { theme } from '../theme';

export const getCentroNotificacionesModalStyles = () => ({
  notiOverlay: {
    position: 'fixed',
    inset: 0,
    background: theme.overlay.modal,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    zIndex: 130,
  },
  notiModal: {
    width: 'min(95vw, 640px)',
    maxHeight: '80vh',
    overflow: 'hidden',
    background: theme.colors.white,
    borderRadius: theme.radius.xl,
    boxShadow: '0 24px 52px rgba(15,23,42,0.22)',
    border: `1px solid ${theme.colors.borderNeutral}`,
    display: 'flex',
    flexDirection: 'column',
  },
  notiHeader: { padding: '12px 14px', borderBottom: `1px solid ${theme.colors.borderNeutral}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px', background: 'linear-gradient(180deg, #ffffff 0%, #f8fbff 100%)' },
  notiTitle: { margin: 0, fontSize: '15px', color: theme.colors.textDark },
  notiActions: { display: 'flex', gap: '8px', alignItems: 'center' },
  notiBtnSmall: { border: 'none', background: 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 100%)', color: theme.colors.white, borderRadius: '999px', padding: '0.48rem 0.85rem', fontSize: '12px', fontWeight: 700, cursor: 'pointer', boxShadow: '0 10px 18px rgba(37,99,235,0.18)' },
  notiBtnClose: { border: 'none', background: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)', color: theme.colors.white, borderRadius: '999px', padding: '0.48rem 0.85rem', fontSize: '12px', fontWeight: 700, cursor: 'pointer', boxShadow: '0 10px 18px rgba(15,23,42,0.18)' },
  notiBody: { padding: '10px', overflowY: 'auto', display: 'grid', gap: '8px' },
  notiItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '10px 12px', background: 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)', boxShadow: '0 8px 18px rgba(148,163,184,0.08)' },
  notiItemNoLeida: { borderColor: '#93c5fd', background: 'linear-gradient(180deg, #eff6ff 0%, #f7fbff 100%)', boxShadow: '0 12px 24px rgba(59,130,246,0.12)' },
  notiItemTitulo: { margin: '0 0 4px 0', fontSize: '13px', fontWeight: 700, color: theme.colors.textDark },
  notiItemMensaje: { margin: '0 0 6px 0', fontSize: '12px', color: theme.colors.textTertiary },
  notiItemMeta: { margin: 0, fontSize: '11px', color: theme.colors.textMuted },
  notiItemBtns: { marginTop: '8px', display: 'flex', justifyContent: 'flex-end' },
  notiEmpty: { margin: 0, padding: '16px', textAlign: 'center', color: theme.colors.textMuted, fontSize: '13px' },
});
