import { theme } from '../theme';

export const getFormularioCertificadoStyles = () => ({
  formularioContenedor: {
    maxWidth: '800px',
    margin: 'clamp(0.75rem, 3vw, 2rem) auto',
    padding: 'clamp(0.9rem, 4vw, 2rem)',
    background: theme.colors.white,
    borderRadius: theme.radius.lg,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  pasoContenedor: {},
  pasoExito: { textAlign: 'center' },
  h2: { color: theme.colors.textStrong, marginBottom: '1.5rem', textAlign: 'center', fontSize: 'clamp(1.15rem, 5vw, 1.7rem)' },
  h3: { color: theme.colors.textSubtle, marginTop: '1.5rem', marginBottom: '1rem', fontSize: '1.1rem' },
  barraProgreso: {
    width: '100%',
    height: '6px',
    background: theme.colors.borderLight,
    borderRadius: '3px',
    marginBottom: '2rem',
    overflow: 'hidden',
  },
  progreso: { height: '100%', background: 'linear-gradient(90deg, #4CAF50, #8BC34A)' },
  opciones: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  botonTramite: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '2rem',
    border: `2px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.lg,
    background: theme.colors.white,
    cursor: 'pointer',
    textAlign: 'center',
  },
  icono: { fontSize: '2.5rem', marginBottom: '0.5rem' },
  titulo: { fontSize: '1.1rem', fontWeight: 'bold', color: theme.colors.textStrong, marginBottom: '0.5rem' },
  descripcion: { fontSize: '0.95rem', color: theme.colors.textSoft },
  formularioGrupo: { marginBottom: '1.5rem' },
  label: { display: 'block', marginBottom: '0.5rem', fontWeight: 600, color: theme.colors.textStrong, fontSize: '0.95rem' },
  input: {
    width: '100%',
    padding: '0.75rem',
    border: `1px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.sm,
    fontSize: '1rem',
    boxSizing: 'border-box',
  },
  inputFile: {
    width: '100%',
    padding: '0.5rem',
    border: `1px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.sm,
    fontSize: '1rem',
    boxSizing: 'border-box',
  },
  archivoCargado: {
    display: 'inline-block',
    marginTop: '0.5rem',
    padding: '0.25rem 0.75rem',
    background: theme.colors.successBg,
    color: theme.colors.successText,
    borderRadius: theme.radius.sm,
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  seccionArchivos: {
    background: theme.colors.adminBg,
    padding: '1.5rem',
    borderRadius: theme.radius.md,
    margin: '1.5rem 0',
  },
  avisoPeso: { margin: '0.25rem 0 0.75rem 0', fontSize: '0.88rem', color: theme.colors.textLight, fontWeight: 600 },
  alertaError: {
    background: theme.colors.dangerBg,
    border: `1px solid ${theme.colors.dangerBorderStrong}`,
    color: theme.colors.dangerPrimary,
    padding: '1rem',
    borderRadius: theme.radius.sm,
    marginBottom: '1.5rem',
    fontWeight: 500,
  },
  resumen: {
    background: theme.colors.panelBg,
    border: `1px solid ${theme.colors.borderLight}`,
    borderRadius: theme.radius.md,
    padding: '1.5rem',
    margin: '2rem 0',
  },
  resumenItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0.75rem 0',
    borderBottom: `1px solid ${theme.colors.borderFaint}`,
    gap: '0.75rem',
    flexWrap: 'wrap',
  },
  resumenItemUltimo: { borderBottom: 'none' },
  botonesAccion: { display: 'flex', gap: '0.75rem', marginTop: '2rem', justifyContent: 'center', flexWrap: 'wrap' },
  botonesFinales: { display: 'flex', gap: '0.75rem', marginTop: '2rem', justifyContent: 'center', flexWrap: 'wrap' },
  botonPrimario: {
    padding: '0.6rem 1.1rem',
    border: 'none',
    borderRadius: theme.radius.sm,
    fontSize: '0.92rem',
    fontWeight: 600,
    cursor: 'pointer',
    background: theme.colors.successPrimary,
    color: theme.colors.white,
    flex: '0 0 auto',
    minWidth: '180px',
    width: 'auto',
    whiteSpace: 'nowrap',
  },
  botonPrimarioDisabled: { background: '#ccc', cursor: 'not-allowed' },
  botonSecundario: {
    padding: '0.6rem 1.1rem',
    border: 'none',
    borderRadius: theme.radius.sm,
    fontSize: '0.92rem',
    fontWeight: 600,
    cursor: 'pointer',
    background: '#f0f0f0',
    color: theme.colors.textStrong,
    flex: '0 0 auto',
    minWidth: '180px',
    width: 'auto',
    whiteSpace: 'nowrap',
  },
  iconoExito: { fontSize: '4rem', color: theme.colors.successPrimary, marginBottom: '1rem' },
  infoRadicacion: { margin: '2rem 0', textAlign: 'left' },
  radicadoPrincipal: {
    background: 'linear-gradient(135deg, #4CAF50, #8BC34A)',
    color: theme.colors.white,
    padding: '2rem',
    borderRadius: theme.radius.lg,
    marginBottom: '2rem',
    textAlign: 'center',
  },
  etiqueta: { margin: 0, fontSize: '0.95rem', opacity: 0.9 },
  numeroRadicado: { fontSize: '2rem', fontWeight: 'bold', margin: '0.5rem 0 0 0', fontFamily: 'Courier New, monospace', letterSpacing: '2px' },
  detalles: { background: theme.colors.panelBg, padding: '1.5rem', borderRadius: theme.radius.md, marginBottom: '1.5rem', borderLeft: `4px solid ${theme.colors.successPrimary}` },
  detalleItem: { display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: `1px solid ${theme.colors.borderFaint}`, gap: '0.75rem', flexWrap: 'wrap' },
  detalleItemUltimo: { borderBottom: 'none' },
  estadoBadge: { display: 'inline-block', background: theme.colors.successPrimary, color: theme.colors.white, padding: '0.25rem 0.75rem', borderRadius: '20px', fontSize: '0.9rem', fontWeight: 600 },
  mensajeConfirmacion: { background: theme.colors.successBg, border: `1px solid ${theme.colors.successBorder}`, padding: '1.5rem', borderRadius: theme.radius.md, margin: '1.5rem 0', color: theme.colors.successText },
  nota: { fontStyle: 'italic', fontSize: '0.95rem', borderTop: `1px solid ${theme.colors.successBorder}`, paddingTop: '0.75rem', marginTop: '0.75rem' },
  proximosPasos: { background: theme.colors.adminBg, padding: '1.5rem', borderRadius: theme.radius.md, marginBottom: '2rem' },
  ol: { margin: 0, paddingLeft: '1.5rem', color: theme.colors.textSubtle },
  li: { marginBottom: '0.75rem', lineHeight: 1.5 },
});
