import { theme } from '../theme';

export const getFormularioCertificadoStyles = () => ({
  formularioContenedor: {
    maxWidth: '800px',
    margin: 'clamp(0.75rem, 3vw, 2rem) auto',
    padding: 'clamp(0.9rem, 4vw, 2rem)',
    background: theme.colors.white,
    borderRadius: theme.radius.xl,
    boxShadow: '0 20px 48px rgba(15,23,42,0.12)',
    border: `1px solid ${theme.colors.borderNeutral}`,
  },
  pasoContenedor: {},
  pasoExito: { textAlign: 'center' },
  h2: { color: theme.colors.textStrong, marginBottom: '1.5rem', textAlign: 'center', fontSize: 'clamp(1.15rem, 5vw, 1.7rem)' },
  h3: { color: theme.colors.textSubtle, marginTop: '1.5rem', marginBottom: '1rem', fontSize: '1.1rem' },
  barraProgreso: {
    width: '100%',
    height: '6px',
    background: theme.colors.borderLight,
    borderRadius: '3px',
    marginBottom: '2rem',
    overflow: 'hidden',
  },
  progreso: { height: '100%', background: 'linear-gradient(90deg, #4CAF50, #8BC34A)' },
  opciones: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  botonTramite: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '2rem',
    border: `2px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.lg,
    background: 'linear-gradient(180deg, #ffffff 0%, #f8fbff 100%)',
    cursor: 'pointer',
    textAlign: 'center',
    boxShadow: '0 14px 24px rgba(148,163,184,0.1)',
  },
  icono: { fontSize: '2.5rem', marginBottom: '0.5rem' },
  titulo: { fontSize: '1.1rem', fontWeight: 'bold', color: theme.colors.textStrong, marginBottom: '0.5rem' },
  descripcion: { fontSize: '0.95rem', color: theme.colors.textSoft },
  formularioGrupo: { marginBottom: '1.5rem' },
  label: { display: 'block', marginBottom: '0.5rem', fontWeight: 600, color: theme.colors.textStrong, fontSize: '0.95rem' },
  input: {
    width: '100%',
    padding: '0.75rem',
    border: `1px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.sm,
    fontSize: '1rem',
    boxSizing: 'border-box',
  },
  inputFile: {
    width: '100%',
    padding: '0.5rem',
    border: `1px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.sm,
    fontSize: '1rem',
    boxSizing: 'border-box',
  },
  archivoCargado: {
    display: 'inline-block',
    marginTop: '0.5rem',
    padding: '0.25rem 0.75rem',
    background: theme.colors.successBg,
    color: theme.colors.successText,
    borderRadius: theme.radius.sm,
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  seccionArchivos: {
    background: 'linear-gradient(180deg, #f8fafc 0%, #f3f7fb 100%)',
    padding: '1.5rem',
    borderRadius: theme.radius.lg,
    margin: '1.5rem 0',
    border: `1px solid ${theme.colors.borderNeutral}`,
  },
  avisoPeso: { margin: '0.25rem 0 0.75rem 0', fontSize: '0.88rem', color: theme.colors.textLight, fontWeight: 600 },
  alertaError: {
    background: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)',
    border: `1px solid ${theme.colors.dangerBorderStrong}`,
    color: theme.colors.dangerPrimary,
    padding: '1rem 1.1rem',
    borderRadius: theme.radius.lg,
    marginBottom: '1.5rem',
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(239,68,68,0.1)',
  },
  resumen: {
    background: 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)',
    border: `1px solid ${theme.colors.borderLight}`,
    borderRadius: theme.radius.lg,
    padding: '1.5rem',
    margin: '2rem 0',
    boxShadow: '0 12px 24px rgba(148,163,184,0.08)',
  },
  resumenItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0.75rem 0',
    borderBottom: `1px solid ${theme.colors.borderFaint}`,
    gap: '0.75rem',
    flexWrap: 'wrap',
  },
  resumenItemUltimo: { borderBottom: 'none' },
  botonesAccion: { display: 'flex', gap: '0.75rem', marginTop: '2rem', justifyContent: 'center', flexWrap: 'wrap' },
  botonesFinales: { display: 'flex', gap: '0.75rem', marginTop: '2rem', justifyContent: 'center', flexWrap: 'wrap' },
  botonPrimario: {
    padding: '0.8rem 1.2rem',
    border: 'none',
    borderRadius: '999px',
    fontSize: '0.92rem',
    fontWeight: 700,
    cursor: 'pointer',
    background: 'linear-gradient(135deg, #166534 0%, #22c55e 100%)',
    color: theme.colors.white,
    flex: '0 0 auto',
    minWidth: '180px',
    width: 'auto',
    whiteSpace: 'nowrap',
    boxShadow: '0 14px 28px rgba(34,197,94,0.22)',
  },
  botonPrimarioDisabled: { background: '#ccc', cursor: 'not-allowed' },
  botonSecundario: {
    padding: '0.8rem 1.2rem',
    border: '1px solid rgba(148,163,184,0.18)',
    borderRadius: '999px',
    fontSize: '0.92rem',
    fontWeight: 700,
    cursor: 'pointer',
    background: 'rgba(255,255,255,0.92)',
    color: theme.colors.textStrong,
    flex: '0 0 auto',
    minWidth: '180px',
    width: 'auto',
    whiteSpace: 'nowrap',
    boxShadow: '0 10px 20px rgba(148,163,184,0.1)',
  },
  iconoExito: { fontSize: '4rem', color: theme.colors.successPrimary, marginBottom: '1rem' },
  infoRadicacion: { margin: '2rem 0', textAlign: 'left' },
  radicadoPrincipal: {
    background: 'linear-gradient(135deg, #166534 0%, #22c55e 55%, #86efac 100%)',
    color: theme.colors.white,
    padding: '2rem',
    borderRadius: theme.radius.lg,
    marginBottom: '2rem',
    textAlign: 'center',
    boxShadow: '0 20px 36px rgba(34,197,94,0.2)',
  },
  etiqueta: { margin: 0, fontSize: '0.95rem', opacity: 0.9 },
  numeroRadicado: { fontSize: '2rem', fontWeight: 'bold', margin: '0.5rem 0 0 0', fontFamily: 'Courier New, monospace', letterSpacing: '2px' },
  detalles: { background: 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)', padding: '1.5rem', borderRadius: theme.radius.lg, marginBottom: '1.5rem', border: `1px solid ${theme.colors.borderNeutral}`, boxShadow: '0 12px 24px rgba(148,163,184,0.08)' },
  detalleItem: { display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: `1px solid ${theme.colors.borderFaint}`, gap: '0.75rem', flexWrap: 'wrap' },
  detalleItemUltimo: { borderBottom: 'none' },
  estadoBadge: { display: 'inline-block', background: theme.colors.successPrimary, color: theme.colors.white, padding: '0.25rem 0.75rem', borderRadius: '20px', fontSize: '0.9rem', fontWeight: 600 },
  mensajeConfirmacion: { background: 'linear-gradient(135deg, #ecfdf5 0%, #dcfce7 100%)', border: `1px solid ${theme.colors.successBorder}`, padding: '1.5rem', borderRadius: theme.radius.lg, margin: '1.5rem 0', color: theme.colors.successText, boxShadow: '0 14px 28px rgba(34,197,94,0.12)' },
  nota: { fontStyle: 'italic', fontSize: '0.95rem', borderTop: `1px solid ${theme.colors.successBorder}`, paddingTop: '0.75rem', marginTop: '0.75rem' },
  proximosPasos: { background: 'linear-gradient(180deg, #f8fafc 0%, #f3f7fb 100%)', padding: '1.5rem', borderRadius: theme.radius.lg, marginBottom: '2rem', border: `1px solid ${theme.colors.borderNeutral}` },
  ol: { margin: 0, paddingLeft: '1.5rem', color: theme.colors.textSubtle },
  li: { marginBottom: '0.75rem', lineHeight: 1.5 },
});
