import { theme } from '../theme';

export const getLoginStyles = () => ({
  loginContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.gradients.alcaldeBackground,
    padding: '20px',
  },
  loginCard: {
    background: theme.colors.white,
    borderRadius: theme.radius.xl,
    boxShadow: '0 24px 60px rgba(15, 23, 42, 0.2)',
    padding: 'clamp(1rem, 5vw, 2.5rem)',
    maxWidth: '450px',
    width: '100%',
    border: `1px solid rgba(255,255,255,0.45)`,
  },
  loginHeader: {
    textAlign: 'center',
    marginBottom: '30px',
  },
  loginHeaderTitle: {
    margin: '0 0 10px 0',
    color: theme.colors.textPrimary,
    fontSize: 'clamp(1.25rem, 5vw, 1.625rem)',
  },
  loginHeaderSubtitle: {
    margin: 0,
    color: theme.colors.textSecondary,
    fontSize: '14px',
  },
  loginError: {
    background: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)',
    border: `1px solid ${theme.colors.dangerBorder}`,
    color: theme.colors.dangerText,
    padding: '12px 14px',
    borderRadius: theme.radius.lg,
    marginBottom: '20px',
    textAlign: 'center',
    boxShadow: '0 12px 24px rgba(239,68,68,0.12)',
  },
  loginErrorText: {
    margin: 0,
    fontSize: '14px',
  },
  loginForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.textPrimary,
  },
  input: {
    padding: '12px 16px',
    border: `1px solid ${theme.colors.borderSoft}`,
    borderRadius: theme.radius.md,
    fontSize: '14px',
    background: '#fbfdff',
  },
  btnLogin: {
    padding: '0.85rem 1.25rem',
    background: 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 60%, #38bdf8 100%)',
    color: theme.colors.white,
    border: 'none',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: '10px',
    width: 'auto',
    alignSelf: 'center',
    minWidth: '180px',
    whiteSpace: 'nowrap',
    boxShadow: '0 16px 28px rgba(37,99,235,0.24)',
  },
  btnLoginDisabled: {
    background: '#bdc3c7',
    cursor: 'not-allowed',
    opacity: 0.6,
  },
  loginFooter: {
    marginTop: '30px',
    textAlign: 'center',
    paddingTop: '20px',
    borderTop: '1px solid #ecf0f1',
  },
  footerText: {
    margin: '8px 0',
    fontSize: '12px',
    color: theme.colors.textSecondary,
  },
});
