import { theme } from '../theme';

export const getPanelConSesionStyles = () => ({
  appVerificar: { minHeight: '100vh', background: theme.gradients.alcaldeBackground },
  appAdmin: { minHeight: '100vh', background: theme.colors.adminBg },
  headerUsuario: { display: 'flex', alignItems: 'center', gap: '0.6rem', marginLeft: 'auto', flexWrap: 'wrap', justifyContent: 'flex-end' },
  btnLogout: {
    padding: '0.5rem 0.95rem',
    background: 'linear-gradient(135deg, rgba(190,24,93,0.92) 0%, rgba(225,29,72,0.9) 100%)',
    color: theme.colors.white,
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: '999px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    boxShadow: '0 10px 20px rgba(127,29,29,0.22)',
  },
  btnCambiarUsuario: {
    padding: '0.5rem 0.95rem',
    background: 'rgba(255,255,255,0.14)',
    color: theme.colors.white,
    border: '1px solid rgba(255,255,255,0.28)',
    borderRadius: '999px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    backdropFilter: 'blur(8px)',
  },
  btnNotificaciones: {
    position: 'relative',
    padding: '0.5rem 0.85rem',
    background: 'linear-gradient(135deg, rgba(255,255,255,0.24) 0%, rgba(255,255,255,0.14) 100%)',
    color: theme.colors.white,
    border: '1px solid rgba(255,255,255,0.35)',
    borderRadius: '999px',
    cursor: 'pointer',
    fontSize: '0.82rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    boxShadow: '0 8px 18px rgba(49,46,129,0.18)',
  },
  btnNotificacionesBrowser: {
    padding: '0.38rem 0.72rem',
    background: 'rgba(255,255,255,0.15)',
    color: theme.colors.white,
    border: `2px solid ${theme.colors.white}`,
    borderRadius: theme.radius.md,
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
  },
  btnNotificacionesBrowserActiva: {
    background: 'rgba(16,185,129,0.35)',
    borderColor: '#34d399',
  },
  badgeNotificaciones: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    minWidth: '18px',
    height: '18px',
    padding: '0 4px',
    borderRadius: '999px',
    background: 'linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)',
    color: theme.colors.white,
    fontSize: '11px',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 10px rgba(127,29,29,0.3)',
  },
});
