import { theme } from '../theme';

export const getPanelConSesionStyles = () => ({
  appVerificar: { minHeight: '100vh', background: theme.gradients.alcaldeBackground },
  appAdmin: { minHeight: '100vh', background: theme.colors.adminBg },
  headerUsuario: { display: 'flex', alignItems: 'center', gap: '0.6rem', marginLeft: 'auto', flexWrap: 'wrap', justifyContent: 'flex-end' },
  btnLogout: {
    padding: '0.38rem 0.72rem',
    background: 'rgba(255,255,255,0.2)',
    color: theme.colors.white,
    border: `2px solid ${theme.colors.white}`,
    borderRadius: theme.radius.md,
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 600,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
  },
  btnCambiarUsuario: {
    padding: '0.38rem 0.72rem',
    background: 'rgba(255,255,255,0.15)',
    color: theme.colors.white,
    border: `2px solid ${theme.colors.white}`,
    borderRadius: theme.radius.md,
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 600,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
  },
  btnNotificaciones: {
    position: 'relative',
    padding: '0.38rem 0.72rem',
    background: 'rgba(255,255,255,0.2)',
    color: theme.colors.white,
    border: `2px solid ${theme.colors.white}`,
    borderRadius: theme.radius.md,
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
  },
  btnNotificacionesBrowser: {
    padding: '0.38rem 0.72rem',
    background: 'rgba(255,255,255,0.15)',
    color: theme.colors.white,
    border: `2px solid ${theme.colors.white}`,
    borderRadius: theme.radius.md,
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 700,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
  },
  btnNotificacionesBrowserActiva: {
    background: 'rgba(16,185,129,0.35)',
    borderColor: '#34d399',
  },
  badgeNotificaciones: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    minWidth: '18px',
    height: '18px',
    padding: '0 4px',
    borderRadius: '999px',
    background: '#ef4444',
    color: theme.colors.white,
    fontSize: '11px',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
