import { theme } from '../theme';

export const getPanelVerificadorStyles = () => ({
  loading: { textAlign: 'center', padding: '40px', fontSize: '16px', color: theme.colors.textSecondary },
  contenedor: { maxWidth: '1600px', margin: '0 auto', padding: 'clamp(0.75rem, 3.5vw, 1.25rem)', background: theme.gradients.verificadorBackground, minHeight: '100vh' },
  header: { background: theme.colors.white, padding: 'clamp(0.9rem, 4vw, 1.5rem)', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, marginBottom: '20px' },
  h2: { margin: '0 0 8px 0', color: theme.colors.textPrimary, fontSize: 'clamp(1.15rem, 5vw, 1.75rem)' },
  subtitle: { margin: 0, color: theme.colors.textSecondary, fontSize: '14px' },
  filtros: { display: 'flex', gap: '8px', marginTop: '14px', flexWrap: 'nowrap', overflowX: 'auto', overflowY: 'hidden', WebkitOverflowScrolling: 'touch' },
  btnFiltro: { border: `1px solid ${theme.colors.borderSoft}`, background: theme.colors.white, color: theme.colors.textPrimary, padding: '6px 10px', borderRadius: theme.radius.lg, cursor: 'pointer', fontWeight: 600, width: 'auto', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flex: '0 0 auto', whiteSpace: 'nowrap', fontSize: '0.85rem' },
  btnFiltroActivo: { background: theme.colors.primaryAction, color: theme.colors.white, borderColor: theme.colors.primaryAction },
  btnConsolidado: { border: 'none', background: theme.colors.primaryAction, color: theme.colors.white, padding: '6px 10px', borderRadius: theme.radius.lg, cursor: 'pointer', fontWeight: 600, marginTop: '8px', width: 'auto', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', whiteSpace: 'nowrap', fontSize: '0.85rem' },
  error: { background: theme.colors.dangerBg, border: `1px solid ${theme.colors.dangerBorder}`, color: theme.colors.dangerText, padding: '16px', borderRadius: theme.radius.lg, marginBottom: '20px' },
  layout: { display: 'grid', gap: '14px' },
  layoutDesktop: { gridTemplateColumns: '420px minmax(0, 1fr)' },
  layoutMobile: { gridTemplateColumns: '1fr' },
  lista: { background: theme.colors.white, padding: '14px', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, height: 'fit-content' },
  listaDesktop: { position: 'sticky', top: '20px' },
  listaTitulo: { margin: '0 0 12px 0', fontSize: '16px', color: theme.colors.textPrimary },
  busquedaWrap: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', flexWrap: 'wrap' },
  busquedaInput: { width: 'min(380px, 100%)', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  busquedaMeta: { margin: 0, fontSize: '12px', color: theme.colors.textMuted },
  busquedaBtn: { padding: '0.35rem 0.75rem', background: theme.colors.primaryButton, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
  listaVacia: { textAlign: 'center', padding: '24px 10px', color: theme.colors.textHint },
  listaScroll: { display: 'flex', flexDirection: 'column', gap: '10px', overflowY: 'auto', overflowX: 'hidden', WebkitOverflowScrolling: 'touch' },
  listaScrollDesktop: { maxHeight: 'calc(100vh - 260px)' },
  listaScrollMobile: { maxHeight: '50vh' },
  item: { padding: '12px', border: `2px solid ${theme.colors.borderSubtle}`, borderRadius: theme.radius.lg, cursor: 'pointer', background: theme.colors.panelBg },
  itemActivo: { borderColor: theme.colors.primaryAccentDark, background: theme.colors.infoBg, boxShadow: theme.shadows.focusInfo },
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', gap: '8px' },
  radicado: { fontWeight: 'bold', color: theme.colors.textPrimary, fontFamily: 'monospace', fontSize: '12px' },
  badge: { fontSize: '11px', padding: '4px 8px', borderRadius: theme.radius.sm, fontWeight: 600, textTransform: 'uppercase' },
  itemP: { margin: '3px 0', fontSize: '13px', color: theme.colors.textPrimary },
  detalle: { background: theme.colors.white, borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, overflow: 'hidden' },
  detalleHeader: { background: theme.gradients.panelHeader, color: theme.colors.white, padding: '18px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  detalleHeaderH3: { margin: 0, fontSize: '18px' },
  cerrar: { background: 'rgba(255,255,255,.2)', border: 'none', color: theme.colors.white, width: '36px', height: '36px', borderRadius: theme.radius.full, cursor: 'pointer', fontSize: '20px' },
  detalleBody: { padding: 'clamp(0.9rem, 3.5vw, 1.2rem)', maxHeight: 'calc(100vh - 230px)', overflowY: 'auto' },
  seccion: { marginBottom: '18px', paddingBottom: '16px', borderBottom: `1px solid ${theme.colors.borderSubtle}` },
  h4: { margin: '0 0 12px 0', fontSize: '15px', color: theme.colors.textPrimary },
  grid2: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px,1fr))', gap: '12px' },
  cardInfo: { background: theme.colors.panelBg, padding: '10px', borderRadius: theme.radius.md, borderLeft: `3px solid ${theme.colors.primaryAccent}` },
  label: { display: 'block', fontSize: '12px', color: theme.colors.textSecondary, textTransform: 'uppercase', fontWeight: 600, marginBottom: '6px' },
  value: { margin: 0, fontSize: '14px', color: theme.colors.textPrimary, fontWeight: 500 },
  input: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '14px', boxSizing: 'border-box' },
  docs: { display: 'flex', flexDirection: 'column', gap: '10px' },
  docItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', padding: '10px', background: theme.colors.panelBg, borderRadius: theme.radius.md, borderLeft: `3px solid ${theme.colors.warningAccent}` },
  docBtns: { display: 'flex', gap: '8px' },
  btnVer: { background: theme.colors.primaryAccent, color: theme.colors.white, border: 'none', padding: '6px 10px', borderRadius: theme.radius.sm, cursor: 'pointer', fontSize: '12px', fontWeight: 600 },
  btnDesc: { background: theme.colors.successStrong, color: theme.colors.white, border: 'none', padding: '6px 10px', borderRadius: theme.radius.sm, cursor: 'pointer', fontSize: '12px', fontWeight: 600 },
  textarea: { width: '100%', minHeight: '110px', padding: '12px', border: `1px solid ${theme.colors.disabled}`, borderRadius: theme.radius.md, fontSize: '13px', boxSizing: 'border-box', resize: 'vertical' },
  acciones: { display: 'flex', gap: '10px', paddingTop: '14px', flexWrap: 'wrap' },
  btnAprobar: { background: theme.colors.successStrong, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, padding: '10px 14px', fontWeight: 600, cursor: 'pointer', width: 'auto', minWidth: '190px' },
  btnRechazar: { background: theme.colors.dangerStrong, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, padding: '10px 14px', fontWeight: 600, cursor: 'pointer', width: 'auto', minWidth: '190px' },
  btnNotificar: { background: theme.colors.warningStrong, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, padding: '10px 14px', fontWeight: 600, cursor: 'pointer', width: 'auto', minWidth: '260px' },
  disabled: { background: theme.colors.disabled, cursor: 'not-allowed', opacity: 0.7 },
  nota: { background: theme.colors.infoBg, borderLeft: `4px solid ${theme.colors.infoBorderStrong}`, padding: '12px', borderRadius: theme.radius.sm, marginTop: '16px', color: theme.colors.infoText, fontSize: '13px' },
  warning: { background: theme.colors.warningBg, borderLeft: `4px solid ${theme.colors.warningStrong}`, padding: '12px', borderRadius: theme.radius.sm, marginBottom: '10px', color: theme.colors.warningTextStrong, fontSize: '13px' },
  certificadosSeccion: { background: theme.colors.white, padding: '14px', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, marginBottom: '14px' },
  filtrosCert: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '8px', marginBottom: '10px' },
  inputFiltro: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  listaCertificados: { display: 'grid', gap: '8px', maxHeight: '220px', overflowY: 'auto' },
  certItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '8px 10px', background: theme.colors.panelBg },
  certMeta: { margin: '2px 0', fontSize: '12px', color: theme.colors.textLight },
  seccionHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.8rem', marginBottom: '10px', flexWrap: 'wrap' },
  btnToggleSeccion: { padding: '0.35rem 0.75rem', background: theme.colors.primaryButton, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
});
