import { theme } from '../theme';

export const getPanelAdminStyles = () => ({
  adminContenedor: { maxWidth: '1200px', margin: '0 auto', padding: 'clamp(0.9rem, 4vw, 2rem)' },
  adminCard: { background: theme.colors.white, borderRadius: theme.radius.lg, padding: 'clamp(1rem, 4vw, 2rem)', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' },
  adminCardTitle: { color: theme.colors.textStrong, marginBottom: '1.5rem' },
  adminBusquedaWrap: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px', flexWrap: 'wrap' },
  adminBusquedaInput: { width: 'min(520px, 100%)', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  adminBusquedaMeta: { margin: 0, fontSize: '12px', color: theme.colors.textMuted },
  adminDetalle: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, background: '#f9fafb', padding: '0.8rem' },
  adminDetalleTitle: { margin: '0 0 0.8rem 0', color: theme.colors.textStrong, fontSize: '1rem' },
  adminDetalleGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '0.6rem 1rem' },
  adminDetalleItem: { margin: 0, color: theme.colors.textTertiary, fontSize: '0.92rem' },
  adminDetalleLabel: { fontWeight: 700, color: theme.colors.textDark },
  tablaWrapper: { overflowX: 'auto', overflowY: 'auto', maxHeight: '420px' },
  tabla: { width: '100%', borderCollapse: 'collapse' },
  th: { padding: '0.75rem', textAlign: 'left', fontWeight: 600, color: theme.colors.textStrong, borderBottom: '2px solid #ddd', background: 'linear-gradient(135deg, #667eea15, #764ba215)' },
  td: { padding: '0.75rem', borderBottom: '1px solid #eee', color: theme.colors.textSecondary },
  celdaRadicado: { fontFamily: 'Courier New, monospace', fontWeight: 'bold', color: '#667eea', letterSpacing: '0.5px' },
  badge: { display: 'inline-block', padding: '0.4rem 0.8rem', borderRadius: '12px', fontSize: '0.85rem', fontWeight: 600 },
  btnVer: { padding: '0.5rem 1rem', background: '#667eea', color: theme.colors.white, border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 },
  usuariosCard: { background: theme.colors.white, borderRadius: theme.radius.lg, padding: 'clamp(1rem, 4vw, 2rem)', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', marginBottom: '1rem' },
  usuariosTitulo: { color: theme.colors.textStrong, marginBottom: '1rem' },
  usuariosGrid: { display: 'grid', gap: '0.75rem' },
  usuarioItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '0.75rem', background: '#fafafa' },
  usuarioFila: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.6rem', alignItems: 'end' },
  usuarioLabel: { display: 'block', fontSize: '12px', color: theme.colors.textMuted, marginBottom: '4px', fontWeight: 600 },
  usuarioInput: { width: '100%', padding: '8px 10px', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, fontSize: '14px', boxSizing: 'border-box' },
  usuarioMeta: { fontSize: '12px', color: theme.colors.textLight, marginTop: '6px' },
  btnGuardarUsuario: { padding: '8px 12px', border: 'none', borderRadius: theme.radius.md, background: '#2563eb', color: theme.colors.white, cursor: 'pointer', fontWeight: 600 },
  btnGuardarUsuarioDisabled: { background: '#9ca3af', cursor: 'not-allowed' },
  seccionHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.8rem', marginBottom: '1rem', flexWrap: 'wrap' },
  btnToggleSeccion: { padding: '0.35rem 0.75rem', background: '#4f46e5', color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
  btnRefrescar: { padding: '0.35rem 0.75rem', background: '#0f766e', color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
  filtrosCert: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '8px', marginBottom: '10px' },
  inputFiltro: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  listaCertificados: { display: 'grid', gap: '8px', maxHeight: '220px', overflowY: 'auto' },
  certItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '8px 10px', background: '#f9fafb' },
  certMeta: { margin: '2px 0', fontSize: '12px', color: theme.colors.textLight },
  adminDocs: { marginTop: '0.9rem', display: 'flex', flexDirection: 'column', gap: '8px' },
  adminDocItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', padding: '8px 10px', border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, background: theme.colors.white },
  adminDocLabel: { color: theme.colors.textStrong, fontSize: '0.9rem', fontWeight: 600 },
  adminDocBtns: { display: 'flex', gap: '8px' },
  btnDocVer: { padding: '6px 10px', border: 'none', borderRadius: theme.radius.md, background: '#2563eb', color: theme.colors.white, cursor: 'pointer', fontWeight: 600, fontSize: '12px' },
  btnDocDesc: { padding: '6px 10px', border: 'none', borderRadius: theme.radius.md, background: '#059669', color: theme.colors.white, cursor: 'pointer', fontWeight: 600, fontSize: '12px' },
  btnNotificarVerificador: { padding: '8px 12px', border: 'none', borderRadius: theme.radius.md, background: '#d97706', color: theme.colors.white, cursor: 'pointer', fontWeight: 600, marginTop: '10px' },
  inputAdminMensaje: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box', marginTop: '10px' },
  adminNota: { marginTop: '8px', fontSize: '12px', color: theme.colors.textMuted },
  adminAuditoria: { marginTop: '1rem', borderTop: '1px dashed #d1d5db', paddingTop: '0.9rem' },
  adminAuditoriaLista: { display: 'grid', gap: '8px', maxHeight: '220px', overflowY: 'auto' },
  adminAuditoriaItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, background: theme.colors.white, padding: '8px 10px' },
  adminAuditoriaMeta: { margin: '2px 0', fontSize: '12px', color: theme.colors.textTertiary },
  adminAuditoriaAccion: { margin: '0 0 4px 0', fontSize: '12px', fontWeight: 700, color: theme.colors.textDark },
  badgeDocsPendientes: { display: 'inline-block', marginTop: '6px', padding: '4px 8px', borderRadius: '999px', background: '#fff3e0', color: '#b45309', fontSize: '11px', fontWeight: 700 },
  badgeDocsOk: { display: 'inline-block', marginTop: '6px', padding: '4px 8px', borderRadius: '999px', background: '#e8f5e9', color: '#15803d', fontSize: '11px', fontWeight: 700 },
  faltantesTexto: { margin: '6px 0 0 0', fontSize: '12px', color: '#92400e' },
});
