import { theme } from '../theme';

export const getPanelAlcaldeStyles = () => ({
  panelCargando: { textAlign: 'center', padding: '40px', fontSize: '16px', color: theme.colors.textSecondary },
  contenedor: {
    maxWidth: '1600px',
    margin: '0 auto',
    padding: 'clamp(0.75rem, 3.5vw, 1.25rem)',
    background: theme.gradients.alcaldeBackground,
    minHeight: '100vh',
  },
  encabezado: {
    background: theme.colors.white,
    padding: 'clamp(0.9rem, 4vw, 1.5rem)',
    borderRadius: theme.radius.xl,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.12)',
    marginBottom: '20px',
    borderLeft: `5px solid ${theme.colors.primary}`,
  },
  h2: { margin: '0 0 8px 0', color: theme.colors.textPrimary, fontSize: 'clamp(1.15rem, 5vw, 1.75rem)' },
  subtitulo: { margin: 0, color: theme.colors.textSecondary, fontSize: '14px' },
  filtros: { marginTop: '14px', display: 'flex', gap: '8px', flexWrap: 'nowrap', overflowX: 'auto', overflowY: 'hidden', WebkitOverflowScrolling: 'touch' },
  btnFiltro: {
    border: `1px solid ${theme.colors.borderSoft}`,
    background: theme.colors.white,
    color: theme.colors.textPrimary,
    padding: '6px 10px',
    borderRadius: theme.radius.lg,
    cursor: 'pointer',
    fontWeight: 600,
    width: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: '0 0 auto',
    whiteSpace: 'nowrap',
    fontSize: '0.85rem',
  },
  btnFiltroActivo: { background: theme.colors.primary, color: theme.colors.white, borderColor: theme.colors.primary },
  panelError: {
    background: theme.colors.dangerBg,
    border: `1px solid ${theme.colors.dangerBorder}`,
    color: theme.colors.dangerText,
    padding: '16px',
    borderRadius: theme.radius.lg,
    marginBottom: '20px',
  },
  panelContenido: { display: 'grid', gap: '14px' },
  panelContenidoDesktop: { gridTemplateColumns: '420px minmax(0, 1fr)' },
  panelContenidoMobile: { gridTemplateColumns: '1fr' },
  panelLista: {
    background: theme.colors.white,
    padding: '14px',
    borderRadius: theme.radius.xl,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    height: 'fit-content',
    position: 'static',
    borderLeft: `4px solid ${theme.colors.primary}`,
  },
  panelListaDesktop: { position: 'sticky', top: '20px' },
  h3Lista: { margin: '0 0 15px 0', fontSize: '16px', color: theme.colors.textPrimary },
  busquedaWrap: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', flexWrap: 'wrap' },
  busquedaInput: { width: 'min(380px, 100%)', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  busquedaMeta: { margin: 0, fontSize: '12px', color: theme.colors.textMuted },
  busquedaBtn: { padding: '0.35rem 0.75rem', background: theme.colors.primaryButton, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
  listaVacia: { textAlign: 'center', padding: '30px 10px', color: theme.colors.successStrong },
  subtexto: { color: theme.colors.textHint, fontSize: '12px', margin: '8px 0 0 0' },
  listaSolicitudes: { display: 'flex', flexDirection: 'column', gap: '10px', overflowY: 'auto', overflowX: 'hidden', WebkitOverflowScrolling: 'touch' },
  listaSolicitudesDesktop: { maxHeight: 'calc(100vh - 300px)' },
  listaSolicitudesMobile: { maxHeight: '50vh' },
  solicitudItem: {
    padding: '15px',
    border: `2px solid ${theme.colors.borderSubtle}`,
    borderRadius: theme.radius.lg,
    cursor: 'pointer',
    background: theme.colors.panelBg,
    borderLeft: `4px solid ${theme.colors.primary}`,
  },
  solicitudActiva: { borderColor: theme.colors.primary, background: theme.colors.primarySoft, boxShadow: theme.shadows.focusPrimary },
  fila: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' },
  radicado: { fontWeight: 'bold', color: theme.colors.primary, fontFamily: 'monospace', fontSize: '13px' },
  badge: { fontSize: '11px', padding: '4px 8px', borderRadius: theme.radius.xl, background: theme.colors.infoBg, color: theme.colors.primary, fontWeight: 600 },
  itemP: { margin: '4px 0', fontSize: '13px' },
  itemStrong: { color: theme.colors.textPrimary, fontSize: '14px' },
  panelDetalle: { background: theme.colors.white, borderRadius: theme.radius.xl, boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)', overflow: 'hidden' },
  detalleHeader: {
    background: theme.gradients.alcaldeBackground,
    color: theme.colors.white,
    padding: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detalleH3: { margin: 0, fontSize: '18px' },
  btnCerrar: {
    background: 'rgba(255, 255, 255, 0.2)',
    border: 'none',
    color: theme.colors.white,
    width: '36px',
    height: '36px',
    borderRadius: theme.radius.full,
    cursor: 'pointer',
    fontSize: '20px',
  },
  contenido: { padding: 'clamp(0.9rem, 3.5vw, 1.5rem)', maxHeight: 'calc(100vh - 220px)', overflowY: 'auto' },
  seccion: { marginBottom: '22px', paddingBottom: '18px', borderBottom: `1px solid ${theme.colors.borderSubtle}` },
  h4: { margin: '0 0 15px 0', fontSize: '15px', color: theme.colors.textPrimary },
  infoGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '12px' },
  infoItem: { background: theme.colors.panelBg, padding: '12px', borderRadius: theme.radius.md, borderLeft: `3px solid ${theme.colors.primary}` },
  label: { display: 'block', fontSize: '12px', color: theme.colors.textSecondary, textTransform: 'uppercase', fontWeight: 600, marginBottom: '6px' },
  infoP: { margin: 0, fontSize: '14px', color: theme.colors.textPrimary, fontWeight: 500 },
  vistaWrap: { border: `2px solid ${theme.colors.borderSubtle}`, borderRadius: theme.radius.lg, padding: '16px', background: theme.colors.white },
  previewFrame: { width: '100%', minHeight: 'min(70vh, 800px)', border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.md, background: theme.colors.white },
  previewTexto: {
    whiteSpace: 'pre-wrap',
    fontFamily: 'Georgia, serif',
    fontSize: '13px',
    lineHeight: 1.7,
    color: theme.colors.textDark,
    background: theme.colors.surfaceSoft,
    border: `1px solid ${theme.colors.borderNeutral}`,
    borderRadius: theme.radius.md,
    padding: '14px',
    margin: 0,
  },
  inputFirma: {
    width: '100%',
    padding: '12px',
    border: `2px solid ${theme.colors.borderSubtle}`,
    borderRadius: theme.radius.md,
    fontSize: '14px',
    fontFamily: 'monospace',
    letterSpacing: '3px',
    boxSizing: 'border-box',
  },
  accionesFirma: { display: 'flex', justifyContent: 'center', marginTop: '20px' },
  btnFirmar: {
    padding: '10px 18px',
    background: theme.gradients.alcaldeBackground,
    color: theme.colors.white,
    border: 'none',
    borderRadius: theme.radius.md,
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    minWidth: '260px',
    width: 'auto',
  },
  btnFirmarDisabled: { background: theme.colors.disabled, cursor: 'not-allowed', opacity: 0.6 },
  infoLegal: { background: theme.colors.legalBg, borderLeft: `4px solid ${theme.colors.legalBorder}`, padding: '12px', borderRadius: theme.radius.sm, marginTop: '20px' },
  infoLegalP: { margin: 0, fontSize: '12px', color: theme.colors.legalText, lineHeight: 1.5 },
  certificadosSeccion: { background: theme.colors.white, padding: '14px', borderRadius: theme.radius.xl, boxShadow: '0 4px 12px rgba(0,0,0,0.1)', marginBottom: '14px' },
  filtrosCert: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '8px', marginBottom: '10px' },
  inputFiltro: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  listaCertificados: { display: 'grid', gap: '8px', maxHeight: '220px', overflowY: 'auto' },
  certItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '8px 10px', background: theme.colors.panelBg },
  certMeta: { margin: '2px 0', fontSize: '12px', color: theme.colors.textLight },
  seccionHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.8rem', marginBottom: '10px', flexWrap: 'wrap' },
  btnToggleSeccion: { padding: '0.35rem 0.75rem', background: theme.colors.primaryButton, color: theme.colors.white, border: 'none', borderRadius: theme.radius.md, cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap' },
});
