import { theme } from '../theme';

export const getPanelVerificadorStyles = () => ({
  loading: { textAlign: 'center', padding: '40px', fontSize: '16px', color: theme.colors.textSecondary },
  contenedor: { maxWidth: '1600px', margin: '0 auto', padding: 'clamp(0.75rem, 3.5vw, 1.25rem)', background: theme.gradients.verificadorBackground, minHeight: '100vh' },
  header: { background: theme.colors.white, padding: 'clamp(0.9rem, 4vw, 1.5rem)', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, marginBottom: '20px' },
  h2: { margin: '0 0 8px 0', color: theme.colors.textPrimary, fontSize: 'clamp(1.15rem, 5vw, 1.75rem)' },
  subtitle: { margin: 0, color: theme.colors.textSecondary, fontSize: '14px' },
  filtros: { display: 'flex', gap: '8px', marginTop: '14px', flexWrap: 'nowrap', overflowX: 'auto', overflowY: 'hidden', WebkitOverflowScrolling: 'touch' },
  btnFiltro: { border: `1px solid ${theme.colors.borderSoft}`, background: '#ffffff', color: theme.colors.textPrimary, padding: '0.55rem 0.95rem', borderRadius: '999px', cursor: 'pointer', fontWeight: 700, width: 'auto', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flex: '0 0 auto', whiteSpace: 'nowrap', fontSize: '0.84rem', boxShadow: '0 6px 14px rgba(148,163,184,0.12)' },
  btnFiltroActivo: { background: 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 55%, #38bdf8 100%)', color: theme.colors.white, borderColor: '#2563eb', boxShadow: '0 12px 24px rgba(37,99,235,0.24)' },
  btnConsolidado: { border: '1px solid rgba(3,105,161,0.18)', background: 'linear-gradient(135deg, #0f766e 0%, #0891b2 100%)', color: theme.colors.white, padding: '0.7rem 1rem', borderRadius: '999px', cursor: 'pointer', fontWeight: 700, marginTop: '8px', width: 'auto', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', whiteSpace: 'nowrap', fontSize: '0.85rem', boxShadow: '0 14px 28px rgba(8,145,178,0.24)' },
  error: { background: theme.colors.dangerBg, border: `1px solid ${theme.colors.dangerBorder}`, color: theme.colors.dangerText, padding: '16px', borderRadius: theme.radius.lg, marginBottom: '20px' },
  layout: { display: 'grid', gap: '14px' },
  layoutDesktop: { gridTemplateColumns: '420px minmax(0, 1fr)' },
  layoutMobile: { gridTemplateColumns: '1fr' },
  lista: { background: theme.colors.white, padding: '14px', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, height: 'fit-content' },
  listaDesktop: { position: 'sticky', top: '20px' },
  listaTitulo: { margin: '0 0 12px 0', fontSize: '16px', color: theme.colors.textPrimary },
  busquedaWrap: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', flexWrap: 'wrap' },
  busquedaInput: { width: 'min(380px, 100%)', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  busquedaMeta: { margin: 0, fontSize: '12px', color: theme.colors.textMuted },
  busquedaBtn: { padding: '0.45rem 0.9rem', background: 'linear-gradient(135deg, #4338ca 0%, #2563eb 100%)', color: theme.colors.white, border: 'none', borderRadius: '999px', cursor: 'pointer', fontWeight: 700, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap', boxShadow: '0 10px 20px rgba(67,56,202,0.18)' },
  listaVacia: { textAlign: 'center', padding: '24px 10px', color: theme.colors.textHint },
  listaScroll: { display: 'flex', flexDirection: 'column', gap: '10px', overflowY: 'auto', overflowX: 'hidden', WebkitOverflowScrolling: 'touch' },
  listaScrollDesktop: { maxHeight: 'calc(100vh - 260px)' },
  listaScrollMobile: { maxHeight: '50vh' },
  item: { padding: '12px', border: `2px solid ${theme.colors.borderSubtle}`, borderRadius: theme.radius.lg, cursor: 'pointer', background: theme.colors.panelBg },
  itemActivo: { borderColor: theme.colors.primaryAccentDark, background: theme.colors.infoBg, boxShadow: theme.shadows.focusInfo },
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', gap: '8px' },
  radicado: { fontWeight: 'bold', color: theme.colors.textPrimary, fontFamily: 'monospace', fontSize: '12px' },
  badge: { fontSize: '11px', padding: '4px 8px', borderRadius: theme.radius.sm, fontWeight: 600, textTransform: 'uppercase' },
  itemP: { margin: '3px 0', fontSize: '13px', color: theme.colors.textPrimary },
  detalle: { background: theme.colors.white, borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, overflow: 'hidden' },
  detalleHeader: { background: theme.gradients.panelHeader, color: theme.colors.white, padding: '18px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  detalleHeaderH3: { margin: 0, fontSize: '18px' },
  cerrar: { background: 'rgba(255,255,255,.18)', border: '1px solid rgba(255,255,255,0.25)', color: theme.colors.white, width: '36px', height: '36px', borderRadius: theme.radius.full, cursor: 'pointer', fontSize: '20px', boxShadow: '0 8px 18px rgba(49,46,129,0.18)' },
  detalleBody: { padding: 'clamp(0.9rem, 3.5vw, 1.2rem)', maxHeight: 'calc(100vh - 230px)', overflowY: 'auto' },
  seccion: { marginBottom: '18px', paddingBottom: '16px', borderBottom: `1px solid ${theme.colors.borderSubtle}` },
  h4: { margin: '0 0 12px 0', fontSize: '15px', color: theme.colors.textPrimary },
  grid2: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px,1fr))', gap: '12px' },
  cardInfo: { background: theme.colors.panelBg, padding: '10px', borderRadius: theme.radius.md, borderLeft: `3px solid ${theme.colors.primaryAccent}` },
  label: { display: 'block', fontSize: '12px', color: theme.colors.textSecondary, textTransform: 'uppercase', fontWeight: 600, marginBottom: '6px' },
  value: { margin: 0, fontSize: '14px', color: theme.colors.textPrimary, fontWeight: 500 },
  input: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '14px', boxSizing: 'border-box' },
  docs: { display: 'flex', flexDirection: 'column', gap: '10px' },
  docItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', padding: '10px', background: theme.colors.panelBg, borderRadius: theme.radius.md, borderLeft: `3px solid ${theme.colors.warningAccent}` },
  docBtns: { display: 'flex', gap: '8px' },
  btnVer: { background: 'linear-gradient(135deg, #2563eb 0%, #3b82f6 100%)', color: theme.colors.white, border: 'none', padding: '0.45rem 0.8rem', borderRadius: '999px', cursor: 'pointer', fontSize: '12px', fontWeight: 700, boxShadow: '0 10px 18px rgba(37,99,235,0.18)' },
  btnDesc: { background: 'linear-gradient(135deg, #15803d 0%, #16a34a 100%)', color: theme.colors.white, border: 'none', padding: '0.45rem 0.8rem', borderRadius: '999px', cursor: 'pointer', fontSize: '12px', fontWeight: 700, boxShadow: '0 10px 18px rgba(22,163,74,0.18)' },
  textarea: { width: '100%', minHeight: '110px', padding: '12px', border: `1px solid ${theme.colors.disabled}`, borderRadius: theme.radius.md, fontSize: '13px', boxSizing: 'border-box', resize: 'vertical' },
  acciones: { display: 'flex', gap: '10px', paddingTop: '14px', flexWrap: 'wrap' },
  btnAprobar: { background: 'linear-gradient(135deg, #166534 0%, #22c55e 100%)', color: theme.colors.white, border: 'none', borderRadius: '999px', padding: '0.8rem 1.1rem', fontWeight: 700, cursor: 'pointer', width: 'auto', minWidth: '190px', boxShadow: '0 14px 28px rgba(34,197,94,0.22)' },
  btnRechazar: { background: 'linear-gradient(135deg, #b91c1c 0%, #ef4444 100%)', color: theme.colors.white, border: 'none', borderRadius: '999px', padding: '0.8rem 1.1rem', fontWeight: 700, cursor: 'pointer', width: 'auto', minWidth: '190px', boxShadow: '0 14px 28px rgba(239,68,68,0.22)' },
  btnNotificar: { background: 'linear-gradient(135deg, #b45309 0%, #f59e0b 100%)', color: '#fffdf7', border: 'none', borderRadius: '999px', padding: '0.8rem 1.1rem', fontWeight: 700, cursor: 'pointer', width: 'auto', minWidth: '260px', boxShadow: '0 14px 28px rgba(245,158,11,0.24)' },
  disabled: { background: theme.colors.disabled, cursor: 'not-allowed', opacity: 0.7 },
  nota: { background: theme.colors.infoBg, borderLeft: `4px solid ${theme.colors.infoBorderStrong}`, padding: '12px', borderRadius: theme.radius.sm, marginTop: '16px', color: theme.colors.infoText, fontSize: '13px' },
  warning: { background: theme.colors.warningBg, borderLeft: `4px solid ${theme.colors.warningStrong}`, padding: '12px', borderRadius: theme.radius.sm, marginBottom: '10px', color: theme.colors.warningTextStrong, fontSize: '13px' },
  certificadosSeccion: { background: theme.colors.white, padding: '14px', borderRadius: theme.radius.xl, boxShadow: theme.shadows.card, marginBottom: '14px' },
  filtrosCert: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '8px', marginBottom: '10px' },
  inputFiltro: { width: '100%', border: `1px solid ${theme.colors.borderSoft}`, borderRadius: theme.radius.md, padding: '8px 10px', fontSize: '13px', boxSizing: 'border-box' },
  listaCertificados: { display: 'grid', gap: '8px', maxHeight: '220px', overflowY: 'auto' },
  certItem: { border: `1px solid ${theme.colors.borderNeutral}`, borderRadius: theme.radius.lg, padding: '8px 10px', background: theme.colors.panelBg },
  certMeta: { margin: '2px 0', fontSize: '12px', color: theme.colors.textLight },
  seccionHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.8rem', marginBottom: '10px', flexWrap: 'wrap' },
  btnToggleSeccion: { padding: '0.45rem 0.85rem', background: 'linear-gradient(135deg, #4338ca 0%, #6366f1 100%)', color: theme.colors.white, border: 'none', borderRadius: '999px', cursor: 'pointer', fontWeight: 700, fontSize: '0.78rem', width: 'auto', whiteSpace: 'nowrap', boxShadow: '0 10px 20px rgba(99,102,241,0.18)' },
});
