import { theme } from '../theme';

export const getVerificadorCertificadoStyles = () => ({
  contenedor: {
    minHeight: '100vh',
    background: theme.gradients.alcaldeBackground,
    padding: 'clamp(0.75rem, 4vw, 2rem) clamp(0.75rem, 4vw, 1rem)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  caja: {
    background: theme.colors.white,
    borderRadius: theme.radius.xl,
    boxShadow: '0 24px 56px rgba(15, 23, 42, 0.18)',
    maxWidth: '600px',
    width: '100%',
    padding: 'clamp(1rem, 4vw, 3rem) clamp(0.9rem, 4vw, 2rem)',
    border: `1px solid rgba(255,255,255,0.45)`,
  },
  encabezado: { textAlign: 'center', marginBottom: '2rem' },
  titulo: { color: theme.colors.textStrong, fontSize: 'clamp(1.2rem, 5vw, 1.8rem)', margin: '0 0 0.5rem 0' },
  subtitulo: { color: theme.colors.textSoft, margin: 0, fontSize: 'clamp(0.9rem, 3.2vw, 1rem)' },
  formulario: { marginBottom: '2rem' },
  entradaRadicado: {
    display: 'flex',
    gap: '0.75rem',
    marginBottom: '2rem',
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  inputRadicado: {
    flex: '1 1 260px',
    width: 'auto',
    minWidth: '220px',
    padding: '1rem 1.25rem',
    border: `2px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.md,
    fontSize: '1.1rem',
    fontFamily: "'Courier New', monospace",
    letterSpacing: '1px',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
    minHeight: '52px',
  },
  botonBuscar: {
    width: 'auto',
    flex: '0 0 auto',
    padding: '1rem 2.25rem',
    background: 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 60%, #38bdf8 100%)',
    color: theme.colors.white,
    border: 'none',
    borderRadius: '999px',
    fontSize: '1.05rem',
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    minHeight: '52px',
    boxShadow: '0 18px 32px rgba(37,99,235,0.22)',
  },
  botonBuscarDisabled: { opacity: 0.6, cursor: 'not-allowed' },
  instrucciones: {
    background: 'linear-gradient(180deg, #f8fafc 0%, #f3f7fb 100%)',
    padding: '1.5rem',
    borderRadius: theme.radius.lg,
    border: '1px solid rgba(125,166,255,0.28)',
  },
  instruccionesTitulo: { marginTop: 0, color: theme.colors.textStrong, fontSize: '1.1rem' },
  instruccionesLista: { margin: 0, paddingLeft: '1.5rem', color: theme.colors.textSoft },
  instruccionesItem: { marginBottom: '0.75rem', lineHeight: 1.5 },
  resultadoError: {
    textAlign: 'center',
    padding: '2rem',
    background: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)',
    borderRadius: theme.radius.xl,
    border: `1px solid ${theme.colors.dangerBorderStrong}`,
    boxShadow: '0 16px 30px rgba(239,68,68,0.1)',
  },
  iconoError: { fontSize: '3rem', marginBottom: '1rem' },
  tituloError: { color: theme.colors.dangerPrimary, margin: '1rem 0 0.5rem 0' },
  textoError: { color: theme.colors.dangerSecondary, margin: '0.5rem 0' },
  resultadoExitoso: {},
  iconoExito: { fontSize: '3rem', color: theme.colors.successPrimary, textAlign: 'center', marginBottom: '1rem' },
  tituloExito: { color: theme.colors.textStrong, textAlign: 'center', margin: '0 0 1.5rem 0', fontSize: '1.5rem' },
  resultadoInfo: { marginBottom: '2rem' },
  infoPrincipal: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  panelPrincipal: {
    background: 'linear-gradient(135deg, #667eea15, #764ba215)',
    padding: '1.5rem',
    borderRadius: theme.radius.lg,
    border: '2px solid #667eea30',
    textAlign: 'center',
  },
  etiquetaPanel: { display: 'block', color: theme.colors.textSoft, fontSize: '0.9rem', marginBottom: '0.5rem', fontWeight: 500 },
  valorRadicado: {
    display: 'block',
    color: theme.colors.textStrong,
    fontSize: '1.2rem',
    fontWeight: 'bold',
    fontFamily: "'Courier New', monospace",
    letterSpacing: '1px',
    wordBreak: 'break-all',
  },
  badgeEstado: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '20px',
    color: theme.colors.white,
    fontWeight: 600,
    fontSize: '1rem',
  },
  resultadoDetalles: {
    background: theme.colors.panelBg,
    padding: '1.5rem',
    borderRadius: theme.radius.lg,
    border: `1px solid ${theme.colors.borderLight}`,
    marginBottom: '1.5rem',
  },
  detalle: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '0.5rem',
    padding: '1rem 0',
    borderBottom: `1px solid ${theme.colors.borderFaint}`,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  detalleUltimo: { borderBottom: 'none' },
  etiquetaDetalle: { color: theme.colors.textSoft, fontWeight: 600, flex: 1 },
  valorDetalle: { color: theme.colors.textStrong, fontWeight: 500, textAlign: 'right', flex: 1 },
  valorVigencia: { padding: '0.25rem 0.75rem', borderRadius: '4px', fontWeight: 'bold' },
  valorVigente: { background: theme.colors.successBg, color: theme.colors.successText },
  valorVencido: { background: theme.colors.dangerBg, color: theme.colors.dangerPrimary },
  alertaBase: { padding: '1rem 1.1rem', borderRadius: theme.radius.lg, marginBottom: '1.5rem', textAlign: 'center', fontWeight: 600, boxShadow: '0 12px 24px rgba(148,163,184,0.08)' },
  alertaVigente: { background: theme.colors.successBg, border: `1px solid ${theme.colors.successBorder}`, color: theme.colors.successText },
  alertaVencido: { background: theme.colors.dangerBg, border: `1px solid ${theme.colors.dangerBorderStrong}`, color: theme.colors.dangerPrimary },
  alertaNoEmitido: { background: theme.colors.infoBg, border: '1px solid #64b5f6', color: theme.colors.infoText },
  alertaRechazado: { background: theme.colors.warningBg, border: `1px solid ${theme.colors.warningBorder}`, color: theme.colors.warningText },
  detallesNoEmitido: { marginTop: '0.5rem', fontSize: '0.9rem', fontStyle: 'italic' },
  botonReiniciar: {
    width: 'auto',
    padding: '0.72rem 1.05rem',
    background: 'linear-gradient(135deg, #4338ca 0%, #6366f1 100%)',
    color: theme.colors.white,
    border: 'none',
    borderRadius: '999px',
    fontSize: '0.92rem',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    boxShadow: '0 12px 22px rgba(99,102,241,0.2)',
  },
  resueltasBloque: { marginTop: '1.5rem', padding: '1rem', border: `1px solid ${theme.colors.borderLight}`, borderRadius: theme.radius.lg, background: '#fafafa' },
  resueltasTitulo: { margin: '0 0 1rem 0', color: theme.colors.textStrong },
  resueltasLista: { display: 'grid', gap: '0.75rem' },
  resueltaItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '0.75rem',
    flexWrap: 'wrap',
    padding: '0.75rem',
    border: `1px solid ${theme.colors.borderNeutral}`,
    borderRadius: theme.radius.md,
    background: theme.colors.white,
  },
  resueltaTexto: { margin: '0.15rem 0', color: theme.colors.textTertiary },
  botonCertificado: {
    border: 'none',
    background: 'linear-gradient(135deg, #15803d 0%, #16a34a 100%)',
    color: theme.colors.white,
    padding: '0.55rem 0.9rem',
    borderRadius: '999px',
    cursor: 'pointer',
    fontWeight: 700,
    boxShadow: '0 10px 18px rgba(22,163,74,0.18)',
  },
  sinCertificado: { color: '#9ca3af', fontSize: '0.9rem' },
  resueltasError: { color: theme.colors.dangerPrimary, margin: 0 },
  resueltasVacio: { margin: 0, color: theme.colors.textSoft },
});
