import { theme } from '../theme';

export const getVistaInicioStyles = () => ({
  appInicio: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: theme.gradients.alcaldeBackground,
  },
  headerInicio: {
    background: 'rgba(0,0,0,0.1)',
    color: theme.colors.white,
    padding: 'clamp(1.5rem, 5vw, 3rem) clamp(1rem, 4vw, 2rem)',
    textAlign: 'center',
  },
  headerMarcaInicio: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.85rem',
  },
  headerTextoInicio: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    textAlign: 'left',
    gap: '0.2rem',
  },
  headerEscudoInicio: {
    width: 'clamp(200px, 30vw, 250px)',
    height: 'auto',
    filter: 'drop-shadow(0 4px 10px rgba(0,0,0,0.25))',
  },
  headerTitle: { fontSize: 'clamp(1.6rem, 6vw, 2.5rem)', margin: 0, fontWeight: 700 },
  headerSubtitle: { fontSize: 'clamp(0.95rem, 3.2vw, 1.1rem)', opacity: 0.9, margin: 0 },
  inicioContenedor: { flex: 1, padding: 'clamp(1rem, 4vw, 3rem) clamp(0.9rem, 4vw, 2rem)', maxWidth: '1200px', margin: '0 auto', width: '100%' },
  intro: { textAlign: 'center', color: theme.colors.white, marginBottom: '3rem' },
  introTitle: { fontSize: 'clamp(1.35rem, 5vw, 2rem)', marginBottom: '0.5rem' },
  introText: { fontSize: 'clamp(0.95rem, 3vw, 1.1rem)', opacity: 0.95, margin: 0 },
  opciones: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem', marginBottom: '2rem' },
  opcionCard: {
    background: theme.colors.white,
    borderRadius: theme.radius.xl,
    padding: 'clamp(1rem, 4vw, 2rem)',
    textAlign: 'center',
    cursor: 'pointer',
    boxShadow: '0 18px 34px rgba(15,23,42,0.12)',
    border: `1px solid ${theme.colors.borderNeutral}`,
  },
  opcionIcono: { fontSize: 'clamp(2rem, 8vw, 3rem)', marginBottom: '1rem' },
  opcionTitulo: { fontSize: 'clamp(1.05rem, 4.3vw, 1.3rem)', color: theme.colors.textStrong, marginBottom: '0.5rem' },
  opcionDesc: { color: theme.colors.textSoft, marginBottom: '1.5rem', fontSize: '0.95rem' },
  opcionBoton: { padding: '0.82rem 2rem', border: 'none', borderRadius: '999px', fontWeight: 700, color: theme.colors.white, cursor: 'pointer', boxShadow: '0 16px 28px rgba(37,99,235,0.18)' },
  infoAdicional: { background: 'rgba(255,255,255,0.95)', padding: 'clamp(1rem, 4vw, 2rem)', borderRadius: '12px', marginBottom: '2rem' },
  infoTitle: { color: theme.colors.textStrong, marginBottom: '1rem', textAlign: 'center' },
  infoList: { listStyle: 'none', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '0.75rem', margin: 0, padding: 0 },
  infoItem: { color: theme.colors.textSubtle, padding: '0.5rem 0' },
  footerInicio: { background: 'rgba(0,0,0,0.2)', color: theme.colors.white, textAlign: 'center', padding: '1.5rem', marginTop: 'auto' },
});
